import type { Terapia } from './tipos'

const grupo1: Terapia[] = [
  {
    slug: 'osatoshi',
    nome: 'Osatoshi',
    nomeCurto: 'Osatoshi',
    tagline: 'Limpeza espiritual de tradição japonesa',
    resumo:
      'Prática espiritual japonesa transmitida pela Shinri, voltada ao que a tradição entende como questões de origem espiritual. É o trabalho ao qual Caio Gracco mais tem se dedicado hoje, realizado presencialmente e à distância.',
    destaque: true,
    ordem: 1,
    acento: 'ouro',
    icone: 'osatoshi',
    origem:
      'O Osatoshi foi desenvolvido no Japão por Masao Utsumi (1943–), que em 2001 recebeu o nome espiritual Reisui Kinsei. Segundo o relato da própria tradição, seus treinamentos espirituais começaram em 1975, no templo do Monte Minobu, e a partir de 1985 ele passou a desenvolver o método. A Associação Shinri — "Associação de Estudos da Verdade = Lei de Deus" — foi fundada formalmente em 15 de outubro de 2006. No Brasil, a expansão é conduzida por Choko Tereza Ito, representante internacional, com sede em Curitiba. Só pode praticar Osatoshi quem passou pela formação e recebeu credenciamento da Shinri.',
    oQueE: [
      'Osatoshi é uma prática espiritual de origem japonesa que se propõe a atuar sobre aquilo que a tradição da Shinri chama de "problemas de origem espiritual": situações de vida que, dentro dessa cosmovisão, estariam ligadas à presença de espíritos perturbadores, a heranças espirituais familiares ou a carmas acumulados. O trabalho é conduzido por terapeutas formados e credenciados pela associação.',
      'É importante situar o Osatoshi no universo de crenças ao qual pertence: trata-se de uma prática espiritual, com cosmovisão própria sobre espíritos, obsessão e salvação — não de um procedimento com base em evidência científica. Para quem se identifica com essa visão de mundo, costuma ser buscado como um cuidado complementar de natureza espiritual, associado a alívio, alento e ressignificação diante de dificuldades persistentes.',
    ],
    comoFunciona: [
      'Segundo a tradição, o terapeuta credenciado atua como intermediário entre a pessoa que pede o trabalho e os espíritos identificados como causadores de perturbação.',
      'Na sessão, o terapeuta busca contato com esses espíritos para orientá-los e encaminhá-los — o que a tradição chama de "salvação" —, aliviando sua influência sobre a vida da pessoa.',
      'Um mesmo atendimento pode envolver o encaminhamento de vários grupos de entidades, conforme relatos da própria associação.',
      'O Omamori é oferecido como prática complementar de autoproteção espiritual, que a própria pessoa pode realizar no dia a dia.',
      'Não há explicação em termos biomédicos: o funcionamento é descrito integralmente dentro do arcabouço de crenças da Shinri.',
    ],
    evidencia:
      'O Osatoshi é uma prática espiritual e religiosa. Não existem estudos científicos revisados por pares que comprovem seus efeitos, e ele não deve ser apresentado nem compreendido como tratamento de saúde.',
    sessao: {
      duracao: 'Varia conforme o atendimento',
      formato: 'À distância, para qualquer lugar do Brasil, ou presencial — com nome completo, data e local de nascimento e a descrição de até três questões principais.',
      sensacao: 'Por ser um trabalho espiritual, a vivência relatada é sobretudo subjetiva: sensação de alívio, leveza, clareza e desanuviamento nos dias seguintes.',
      frequencia: 'A tradição recomenda um ciclo de três atendimentos, com cerca de uma semana de intervalo entre eles.',
      distancia: 'sim',
    },
    indicacoes: [
      'Sensação de estar "travado" sem explicação aparente',
      'Dificuldades que se repetem em ciclos, sem desfecho',
      'Questões financeiras recorrentes',
      'Conflitos e padrões repetidos em relacionamentos',
      'Sensação de peso, cansaço ou desconforto energético',
      'Ambientes — casa, sala comercial — que parecem "carregados"',
      'Interesse em práticas de proteção espiritual',
      'Períodos de luto e transição',
      'Harmonização de negócios e ambientes de trabalho',
      'Continuidade de trabalhos espirituais já iniciados',
    ],
    limites:
      'O Osatoshi não é tratamento médico, psicológico ou psiquiátrico e não substitui nenhum deles. Depressão, ansiedade, pensamentos de morte, dores persistentes e qualquer sintoma físico ou mental devem ser avaliados por profissionais habilitados. Quem já está em acompanhamento de saúde mental não deve interrompê-lo. A prática está vinculada a uma cosmovisão religiosa específica — não se identificar com ela é legítimo.',
    faq: [
      { pergunta: 'O Osatoshi tem comprovação científica?', resposta: 'Não. É uma prática espiritual fundamentada nas crenças da Shinri, sem estudos científicos que comprovem seus efeitos. Ela é oferecida como cuidado espiritual complementar, nunca como tratamento de saúde.' },
      { pergunta: 'Preciso acreditar em espíritos para receber um Osatoshi?', resposta: 'A prática parte de uma cosmovisão específica sobre espíritos e carma. Ela faz mais sentido para quem se identifica com esse universo — e não há problema algum em não se identificar.' },
      { pergunta: 'A sessão pode ser feita totalmente online?', resposta: 'Sim. O Osatoshi é tradicionalmente realizado à distância, a partir do nome completo, data e local de nascimento e da descrição das questões que a pessoa quer trabalhar.' },
      { pergunta: 'Quantos atendimentos são recomendados?', resposta: 'Em geral, um ciclo de três, com cerca de uma semana de intervalo entre eles. A avaliação de continuidade é feita ao longo do processo.' },
      { pergunta: 'O Osatoshi substitui terapia psicológica ou tratamento médico?', resposta: 'Não, em nenhuma hipótese. É um cuidado de natureza espiritual, que pode caminhar ao lado do acompanhamento de saúde — nunca no lugar dele.' },
      { pergunta: 'Qualquer pessoa pode aplicar Osatoshi?', resposta: 'Não. É necessário passar pela formação e ser credenciado pela Shinri. Caio Gracco é terapeuta credenciado, listado no site oficial da Shinri do Brasil.' },
      { pergunta: 'Quais informações preciso enviar antes?', resposta: 'Nome completo, data de nascimento e local de nascimento, além da descrição de até três questões que você quer trabalhar. Escreva com suas palavras, do jeito que a coisa aparece na sua vida — não é preciso usar termo técnico nenhum.' },
      { pergunta: 'Preciso estar acordado ou em algum lugar específico na hora do atendimento?', resposta: 'Não. O trabalho é conduzido pelo terapeuta e não exige que você esteja em posição, horário ou local determinado. Muita gente prefere reservar um tempo tranquilo no dia, mas isso é escolha sua, não exigência da prática.' },
      { pergunta: 'Preciso fazer alguma preparação antes?', resposta: 'Não há jejum, restrição alimentar nem ritual obrigatório. O que costuma ajudar é organizar antes, por escrito, o que você quer tratar — chegar com as questões claras torna a conversa mais objetiva.' },
      { pergunta: 'O Osatoshi tem contraindicação?', resposta: 'Como não envolve toque, agulha, substância ou manipulação física, não há contraindicação clínica. A ressalva é outra: quem está em sofrimento psíquico intenso — crises de ansiedade, depressão, pensamentos de morte — precisa de avaliação profissional de saúde, e o Osatoshi não ocupa esse lugar.' },
      { pergunta: 'Posso pedir um Osatoshi para outra pessoa?', resposta: 'A prática é conduzida a partir dos dados e das questões de quem vai receber, então o ideal é que a própria pessoa saiba e concorde. Pedir um trabalho para alguém sem que essa pessoa queira não é o caminho.' },
      { pergunta: 'E se eu não sentir nada depois da sessão?', resposta: 'Acontece, e não significa que algo deu errado. As percepções relatadas variam muito: algumas pessoas descrevem alívio nos dias seguintes, outras não notam nada de imediato. O Osatoshi não garante sensação nem resultado.' },
      { pergunta: 'Posso fazer Osatoshi junto com Reiki, terapia ou tratamento médico?', resposta: 'Sim. Não há incompatibilidade com outras práticas nem com acompanhamento de saúde. O que não se deve fazer, em nenhuma hipótese, é interromper medicação, consulta ou terapia por causa de um atendimento espiritual.' },
      { pergunta: 'Dá para fazer um trabalho para a casa ou para o comércio?', resposta: 'Sim, a tradição prevê trabalhos voltados a ambientes — residência, sala comercial, negócio. Vale o mesmo enquadramento: é cuidado espiritual dentro da cosmovisão da Shinri, não uma solução para questões estruturais, financeiras ou jurídicas do lugar.' },
    ],
    termos: [
      { termo: 'Shinri', definicao: 'Associação espiritual japonesa cujo nome significa "Verdade = Lei de Deus", dentro da qual o Osatoshi é ensinado e transmitido.' },
      { termo: 'Osatoshi', definicao: 'Método de trabalho espiritual da Shinri, voltado ao que a tradição chama de salvação e encaminhamento de espíritos.' },
      { termo: 'Omamori', definicao: 'Prática complementar de autoproteção espiritual, realizada pela própria pessoa no dia a dia.' },
      { termo: 'Kisha', definicao: 'Nome dado à contribuição financeira que acompanha um atendimento de Osatoshi.' },
      { termo: 'Reisui Kinsei', definicao: 'Nome espiritual recebido em 2001 por Masao Utsumi, fundador da Shinri.' },
      { termo: 'Salvação de espíritos', definicao: 'Na tradição, o ato de orientar e encaminhar entidades consideradas perturbadoras, aliviando sua influência sobre a pessoa.' },
      { termo: 'Terapeuta credenciado', definicao: 'Praticante que concluiu a formação da Shinri e está autorizado a conduzir atendimentos de Osatoshi.' },
      { termo: 'Carma', definicao: 'Na cosmovisão da tradição, o acúmulo de consequências de ações passadas — desta ou de outras vidas — que se refletiria na vida presente.' },
    ],
    keywords: ['o que é osatoshi', 'osatoshi terapia japonesa', 'sessão de osatoshi online', 'osatoshi à distância', 'limpeza espiritual japonesa', 'shinri osatoshi', 'omamori proteção espiritual', 'terapeuta osatoshi credenciado', 'osatoshi para negócios', 'desobsessão espiritual japonesa'],
    fontes: [
      { titulo: 'Shinri do Brasil — O trabalho de Osatoshi', url: 'https://www.osatoshi.com.br/o-trabalho-de-osatoshi' },
      { titulo: 'Shinri do Brasil — Sr. Masao Utsumi', url: 'https://www.osatoshi.com.br/masao-utsumi-bio' },
      { titulo: 'Shinri do Brasil — Terapeutas credenciados', url: 'https://www.osatoshi.com.br/terapeutas-credenciados' },
    ],
  },
  {
    slug: 'emf-balancing-technique',
    nome: 'EMF Balancing Technique®',
    nomeCurto: 'EMF Balancing',
    tagline: 'Calibração do seu campo',
    resumo:
      'Sistema energético criado por Peggy Phoenix Dubro, baseado na ideia de uma "malha de calibração universal" ao redor do corpo. A pessoa permanece vestida e a sessão é conduzida com movimentos suaves, com pouco ou nenhum toque.',
    destaque: true,
    ordem: 2,
    acento: 'violeta',
    icone: 'emf',
    origem:
      'A EMF Balancing Technique® foi desenvolvida a partir de 1988 nos Estados Unidos por Peggy Phoenix Dubro, terapeuta e escritora norte-americana. Não é uma tradição milenar: é um sistema autoral contemporâneo, formalizado em um programa de treze fases e difundido internacionalmente por praticantes licenciados. EMF é a sigla de Electro-Magnetic Field — campo eletromagnético.',
    oQueE: [
      'A EMF Balancing Technique® trabalha com a ideia de que existe, ao redor do corpo humano, uma anatomia energética chamada Malha de Calibração Universal (Universal Calibration Lattice, ou UCL) — linhas de energia que se estenderiam até cerca de dois metros do corpo físico. Na sessão, o praticante realiza movimentos precisos e suaves dentro e ao redor dessa malha, com a intenção de calibrá-la.',
      'A vivência acontece com a pessoa totalmente vestida, deitada ou sentada, e costuma ser descrita como tranquila e profundamente relaxante. É apresentada como ferramenta de autodesenvolvimento e ampliação da consciência — não como procedimento de saúde com efeito clínico comprovado.',
    ],
    comoFunciona: [
      'Segundo a tradição da técnica, a UCL registraria a história pessoal, os potenciais e a capacidade de dar e receber de cada indivíduo.',
      'O praticante executa movimentos energéticos específicos — lembram um tai chi lento — dentro e ao redor dessa malha.',
      'O programa completo tem treze fases, cada uma com um foco próprio; muitas pessoas iniciam pelas quatro primeiras.',
      'Calibrar a malha, na proposta da técnica, ampliaria a capacidade de sustentar clareza, equilíbrio emocional e alinhamento com o propósito de vida.',
    ],
    evidencia:
      'Não há evidência científica da existência da Malha de Calibração Universal nem estudos clínicos controlados sobre os efeitos atribuídos à técnica. Os relatos de benefício são subjetivos e variam de pessoa para pessoa.',
    sessao: {
      duracao: 'Cerca de 60 minutos',
      formato: 'A pessoa permanece totalmente vestida, deitada nas fases iniciais e sentada nas finais. Há pouco ou nenhum toque físico direto.',
      sensacao: 'Relaxamento profundo, aquecimento ou formigamento em algumas regiões, sensação de expansão e clareza mental.',
      frequencia: 'São treze fases ao todo. É comum começar pelas fases I a IV, que formam um ciclo introdutório completo.',
      distancia: 'sim',
    },
    indicacoes: [
      'Estresse e ansiedade do dia a dia',
      'Busca por clareza mental e foco',
      'Apoio emocional em transições de vida',
      'Processos de autoconhecimento',
      'Sensação de desalinhamento interior',
      'Relaxamento profundo e bem-estar geral',
      'Questões ligadas a propósito e direção de vida',
      'Complemento a psicoterapia e outros acompanhamentos',
    ],
    limites:
      'A EMF Balancing Technique® não é procedimento médico, fisioterapêutico ou psicológico. Não trata, não diagnostica e não cura doenças, e não substitui consulta ou tratamento médico, psicológico ou psiquiátrico.',
    faq: [
      { pergunta: 'A técnica tem comprovação científica?', resposta: 'Não. É uma prática energética contemporânea, sem estudos controlados que comprovem seus efeitos. É oferecida como recurso de bem-estar e autodesenvolvimento.' },
      { pergunta: 'Preciso tirar a roupa?', resposta: 'Não. A pessoa permanece totalmente vestida durante toda a sessão. Recomenda-se roupa confortável.' },
      { pergunta: 'Pode ser feita online?', resposta: 'Sim, é comumente oferecida à distância, por videochamada.' },
      { pergunta: 'Quantas sessões são necessárias?', resposta: 'O programa completo tem treze fases. Muitas pessoas iniciam pelas quatro primeiras, que já formam um ciclo com sentido próprio.' },
      { pergunta: 'É desconfortável?', resposta: 'Não. A experiência é descrita como tranquila e relaxante, sem manipulação física ou pressão.' },
      { pergunta: 'O que significa "calibrar o campo"?', resposta: 'É a linguagem própria da técnica para descrever os movimentos realizados ao redor do corpo, com a intenção de reorganizar aquilo que ela chama de malha energética pessoal.' },
      { pergunta: 'Preciso me preparar de alguma forma antes?', resposta: 'Não há preparo obrigatório. Vale escolher roupa confortável, evitar chegar com pressa e desligar o celular. Se for online, garanta um lugar onde você possa ficar deitado ou sentado sem interrupção pelo tempo da sessão.' },
      { pergunta: 'Posso comer antes da sessão?', resposta: 'Pode. Não há restrição alimentar. A recomendação prática é evitar refeição muito pesada logo antes, só porque isso costuma deixar a pessoa sonolenta ou desconfortável deitada.' },
      { pergunta: 'Tem alguma contraindicação?', resposta: 'Por não envolver pressão, manipulação, agulha ou substância, o risco físico é praticamente nulo. A ressalva importante é de contexto: quem tem sintomas físicos ou psíquicos persistentes precisa de avaliação profissional, e a sessão não deve adiar essa avaliação.' },
      { pergunta: 'Grávida pode fazer?', resposta: 'Não há manipulação física nem estímulo de pontos, então a prática costuma ser considerada compatível com a gestação. Ainda assim, informe o terapeuta e converse com quem acompanha o pré-natal antes de iniciar qualquer prática nova.' },
      { pergunta: 'A EMF Balancing trata ansiedade ou depressão?', resposta: 'Não. Ela não trata, não diagnostica e não cura transtorno nenhum. Muitas pessoas relatam relaxamento e sensação de clareza depois da sessão, mas ansiedade e depressão pedem acompanhamento com profissional de saúde mental.' },
      { pergunta: 'E se eu não sentir nada durante a sessão?', resposta: 'É comum e não indica falha. As percepções descritas — calor, formigamento, expansão — variam muito de pessoa para pessoa, e há quem só relate um relaxamento discreto. Nada na técnica depende de você sentir algo específico.' },
      { pergunta: 'Posso combinar com Reiki, psicoterapia ou tratamento médico?', resposta: 'Sim, não há incompatibilidade. A EMF Balancing é um recurso de bem-estar que caminha ao lado do que você já faz. Nenhum medicamento, consulta ou terapia deve ser interrompido por causa dela.' },
      { pergunta: 'Quem pode aplicar a técnica?', resposta: 'É uma marca registrada de organização privada, e a aplicação é feita por praticantes que passaram pelo treinamento oficial de cada fase. Vale perguntar ao profissional por qual formação ele passou e até que fase está habilitado.' },
      { pergunta: 'Quanto tempo esperar entre uma fase e outra?', resposta: 'Não existe intervalo rígido. É comum deixar alguns dias ou uma semana entre as fases iniciais, para dar tempo de perceber como cada uma repercute. O ritmo é combinado caso a caso.' },
    ],
    termos: [
      { termo: 'UCL — Malha de Calibração Universal', definicao: 'Estrutura energética que, segundo a técnica, envolve o corpo e é o foco do trabalho.' },
      { termo: 'Calibração', definicao: 'Processo de ajuste energético promovido pelos movimentos do praticante ao redor do corpo.' },
      { termo: 'Fases I a XIII', definicao: 'As treze etapas sequenciais do programa completo da EMF Balancing Technique®.' },
      { termo: 'Core Star', definicao: 'Na linguagem da técnica, o núcleo energético central da pessoa, trabalhado nas fases mais avançadas.' },
      { termo: 'Malha Cósmica', definicao: 'Campo energético mais amplo ao qual a malha pessoal estaria conectada, segundo a proposta da técnica.' },
      { termo: 'Fase I — Sabedoria e Emoção', definicao: 'Primeira fase, voltada à harmonização entre razão e emoção.' },
      { termo: 'Fase II — Honrando a História', definicao: 'Fase dedicada à ressignificação de experiências do passado.' },
      { termo: 'Fase III — Energia do Centro', definicao: 'Fase voltada à conexão com o centro energético pessoal.' },
      { termo: 'Fase IV — Potenciais', definicao: 'Fase de alinhamento com potenciais e intenções para o futuro.' },
    ],
    keywords: ['emf balancing technique o que é', 'calibração do campo eletromagnético', 'malha de calibração universal', 'peggy phoenix dubro', 'sessão emf balancing online', 'fases emf balancing technique', 'terapia energética emf', 'terapeuta emf balancing brasil'],
    fontes: [
      { titulo: 'Peggy Phoenix Dubro — site oficial', url: 'https://peggyphoenixdubro.com/emf/' },
      { titulo: 'EMF Worldwide — origem da técnica', url: 'https://www.emfbalancingtechnique.com/peggy/origin_of_emfbt.php?phpLang=pt' },
    ],
  },
  {
    slug: 'elementoterapia-magnetica',
    nome: 'Elementoterapia Magnética',
    nomeCurto: 'Elementoterapia',
    tagline: 'Ímãs e elementos naturais em conjunto',
    resumo:
      'Sistematização brasileira que combina ímãs terapêuticos com elementos naturais — cristais, plantas, florais — buscando equilíbrio em cinco planos: biológico, emocional, mental, psicológico e espiritual.',
    destaque: true,
    ordem: 3,
    acento: 'magenta',
    icone: 'elementoterapia',
    origem:
      'A Elementoterapia Magnética foi sistematizada por Karoly Vieira Jardim, biomagnetista, diretora da Magnetium, a partir de estudos de alquimia, filosofia e fitoterapia. Insere-se no campo mais amplo do biomagnetismo e das chamadas PICMAG — Práticas Integrativas e Complementares Magnéticas. É uma sistematização recente e brasileira, distinta do biomagnetismo clássico mexicano de Isaac Goiz Durán.',
    oQueE: [
      'A Elementoterapia Magnética combina o uso de ímãs posicionados em pontos do corpo com outros elementos naturais — cristais, pedras, plantas e florais —, buscando equilíbrio em cinco planos que a técnica considera interligados: biológico, emocional, mental, psicológico e espiritual. A premissa é que um desequilíbrio em um desses planos se reflete nos demais.',
      'Na prática, o terapeuta trabalha com protocolos que combinam o posicionamento dos ímãs a recursos como florais magnéticos, aromas e música. É apresentada como cuidado natural complementar de bem-estar — nunca como substituto de acompanhamento de saúde.',
    ],
    comoFunciona: [
      'Segundo a proposta da técnica, o magnetismo dos ímãs combinado a elementos naturais favoreceria processos de limpeza, reequilíbrio e autorregulação.',
      'O trabalho parte da leitura das cinco esferas interligadas, buscando causas e não apenas sintomas.',
      'Os protocolos são escolhidos conforme a queixa e a avaliação inicial, e podem incluir florais magnéticos e outros recursos complementares.',
    ],
    evidencia:
      'Não há evidência científica reconhecida de que ímãs terapêuticos de baixa intensidade produzam os efeitos amplos descritos pela técnica. Os estudos sobre magnetoterapia em geral são limitados e inconclusivos. Afirmações amplas de eficácia pertencem à tradição da técnica, não à literatura científica.',
    sessao: {
      duracao: 'Varia conforme o protocolo',
      formato: 'Presencial, com posicionamento de ímãs em pontos específicos do corpo, podendo incluir florais e outros elementos naturais.',
      sensacao: 'Relaxamento, leveza e conforto durante e após a aplicação.',
      frequencia: 'Definida caso a caso, conforme o protocolo e a avaliação do terapeuta.',
      distancia: 'parcial',
    },
    indicacoes: [
      'Tensão e sobrecarga emocional',
      'Dificuldade para dormir',
      'Dores de cabeça recorrentes',
      'Desconfortos digestivos ligados à tensão',
      'Cansaço e falta de disposição',
      'Períodos de estresse prolongado',
      'Busca por cuidado natural complementar',
      'Acompanhamento de processos de mudança de hábitos',
    ],
    limites:
      'A Elementoterapia Magnética não é tratamento médico, não diagnostica e não cura doenças. Pessoas com marca-passo, implantes eletrônicos, gestantes e quem tem condições de saúde específicas devem consultar o médico antes de qualquer terapia com ímãs, e informar o terapeuta.',
    faq: [
      { pergunta: 'Terapia com ímãs tem comprovação científica?', resposta: 'Os estudos sobre magnetoterapia são limitados e inconclusivos. A prática é oferecida como recurso complementar de bem-estar, não como tratamento de saúde.' },
      { pergunta: 'Ímãs no corpo podem fazer mal?', resposta: 'Ímãs externos de baixa intensidade costumam ter risco baixo, mas quem tem marca-passo, bomba de insulina ou outro implante eletrônico deve consultar o médico antes e informar o terapeuta.' },
      { pergunta: 'Pode ser feita à distância?', resposta: 'A aplicação dos ímãs é presencial. Orientações iniciais e conversas de avaliação podem ser feitas online.' },
      { pergunta: 'Quem criou a técnica?', resposta: 'Karoly Vieira Jardim, biomagnetista e diretora da Magnetium, no Brasil.' },
      { pergunta: 'Substitui remédios ou tratamento médico?', resposta: 'Não, em nenhuma hipótese. Nenhum medicamento deve ser suspenso por causa de uma sessão.' },
      { pergunta: 'O que são florais magnéticos?', resposta: 'São preparações da terapia floral que, nessa abordagem, são combinadas ao trabalho com ímãs dentro dos protocolos da técnica.' },
      { pergunta: 'Os ímãs ficam colados no corpo depois da sessão?', resposta: 'Depende do protocolo. Em algumas aplicações os ímãs são posicionados apenas durante o atendimento; em outras, o terapeuta pode orientar o uso por um período em casa. Isso é combinado na hora e você deve sair sabendo exatamente o que fazer.' },
      { pergunta: 'Preciso tirar a roupa?', resposta: 'Não. A aplicação é feita com você vestido, com os ímãs posicionados sobre a roupa ou sobre a pele em áreas de fácil acesso. Roupa leve e confortável facilita.' },
      { pergunta: 'A Elementoterapia Magnética emagrece?', resposta: 'Não. Nenhuma aplicação de ímãs emagrece, e prometer isso seria desonesto. Perda de peso envolve alimentação, atividade física e acompanhamento profissional — nutricionista e médico.' },
      { pergunta: 'Posso fazer se tomo remédio de uso contínuo?', resposta: 'Sim, e é fundamental contar ao terapeuta quais medicações você usa. A sessão não interfere no efeito dos remédios e, principalmente, nenhuma dose deve ser reduzida ou suspensa por causa dela. Só o médico que prescreveu pode alterar um tratamento.' },
      { pergunta: 'Grávida pode fazer?', resposta: 'Gestantes devem conversar com o médico que acompanha o pré-natal antes e informar a gravidez ao terapeuta. Na dúvida, o cuidado prudente é adiar ou optar por práticas mais bem estabelecidas para esse período.' },
      { pergunta: 'O que eu sinto durante a aplicação?', resposta: 'Os relatos mais comuns são de relaxamento, leve calor ou formigamento no ponto onde o ímã está, e sonolência. Muita gente não sente nada em particular além de estar deitada e tranquila — o que também é esperado.' },
      { pergunta: 'Quantas sessões costumam ser feitas?', resposta: 'Não existe número padrão. O terapeuta define conforme a avaliação inicial e a queixa, e é razoável reavaliar depois de algumas sessões se faz sentido continuar. Desconfie de pacote fechado longo vendido antes de qualquer avaliação.' },
      { pergunta: 'Dá para combinar com acupuntura, Reiki ou psicoterapia?', resposta: 'Sim, não há conflito entre elas. O que vale sempre é contar a cada profissional o que você está fazendo, para que o cuidado seja coerente no conjunto.' },
    ],
    termos: [
      { termo: 'Elementoterapia Magnética', definicao: 'Abordagem que combina magnetismo terapêutico com elementos naturais como cristais, plantas e florais.' },
      { termo: 'Biomagnetismo', definicao: 'Campo mais amplo das práticas que utilizam ímãs com finalidade terapêutica.' },
      { termo: 'Cinco esferas do ser', definicao: 'Modelo da técnica que considera as dimensões biológica, emocional, mental, psicológica e espiritual como interligadas.' },
      { termo: 'Protocolo', definicao: 'Conjunto padronizado de posicionamento de ímãs e recursos complementares para uma determinada finalidade.' },
      { termo: 'Florais magnéticos', definicao: 'Recurso que une a terapia floral ao trabalho com ímãs dentro da abordagem.' },
      { termo: 'PICMAG', definicao: 'Sigla de Práticas Integrativas e Complementares Magnéticas.' },
      { termo: 'Magnetoterapia', definicao: 'Uso de campos magnéticos com finalidade terapêutica.' },
    ],
    keywords: ['elementoterapia magnética o que é', 'terapia com ímãs', 'biomagnetismo terapêutico', 'florais magnéticos', 'karoly jardim elementoterapia', 'terapia magnética natural', 'terapeuta elementoterapia magnética'],
    fontes: [{ titulo: 'Magnetium — Elementoterapia Magnética', url: 'https://magnetium.com.br/' }],
  },
]

const grupo2: Terapia[] = [
  {
    slug: 'reiki',
    nome: 'Reiki',
    nomeCurto: 'Reiki',
    tagline: 'Imposição de mãos e relaxamento profundo',
    resumo:
      'Prática japonesa de imposição de mãos criada por Mikao Usui em 1922. A pessoa permanece deitada e vestida enquanto o terapeuta posiciona as mãos sobre ou próximo ao corpo. Integra as práticas do SUS desde 2017.',
    destaque: false,
    ordem: 4,
    acento: 'agua',
    icone: 'reiki',
    origem:
      'O Reiki foi desenvolvido no Japão por Mikao Usui (1865–1926), que em 1922 fundou em Tóquio a Usui Reiki Ryoho Gakkai. A linhagem mais difundida no Ocidente passa por Chujiro Hayashi (1880–1940) e por Hawayo Takata (1900–1980), responsável por levar o Reiki aos Estados Unidos. Chegou ao Brasil pelas décadas de 1980 e 1990. O nome vem do japonês rei (universal) e ki (energia vital).',
    oQueE: [
      'O Reiki é uma prática de imposição de mãos: o terapeuta posiciona as mãos sobre ou próximo ao corpo da pessoa, sem exercer pressão, com a intenção de canalizar aquilo que a tradição chama de energia vital universal. A pessoa permanece deitada e vestida durante toda a sessão, em ambiente silencioso e acolhedor.',
      'Diferente de terapias manuais como o Shiatsu, o Reiki não envolve manipulação física, pressão ou massagem. É uma prática sutil, baseada na presença e na intenção, que segue sequências de posições de mãos sobre a cabeça, o tronco e as demais regiões do corpo.',
    ],
    comoFunciona: [
      'Segundo a tradição, existe uma energia vital universal que pode ser canalizada pelas mãos de quem passou pelo processo de sintonização, transmitido por um mestre.',
      'Essa energia, ao ser canalizada, favoreceria relaxamento, redução do estresse e reequilíbrio geral, apoiando os mecanismos naturais de autorregulação do corpo.',
      'Na tradição, entende-se que a energia flui para onde é necessária, sem que o praticante precise direcioná-la conscientemente.',
    ],
    evidencia:
      'A evidência científica sobre o Reiki é limitada e heterogênea. Alguns estudos sugerem redução da ansiedade e da dor percebida em contextos como cuidados paliativos e pré e pós-operatório, mas revisões mais rigorosas apontam qualidade metodológica baixa e alto risco de viés. Não há comprovação do mecanismo energético proposto pela tradição. O Reiki integra a Política Nacional de Práticas Integrativas e Complementares do SUS desde a Portaria GM/MS nº 849/2017 — o que representa reconhecimento institucional como recurso de cuidado, e não validação científica de eficácia.',
    sessao: {
      duracao: '45 a 60 minutos',
      formato: 'A pessoa permanece deitada e vestida, geralmente de olhos fechados, com música suave ao fundo. O toque é leve ou inexistente.',
      sensacao: 'Muitos relatam calor, formigamento ou peso sob as mãos do terapeuta, além de relaxamento profundo. As sensações variam bastante — algumas pessoas sentem apenas o relaxamento.',
      frequencia: 'Pode ser pontual ou em ciclos semanais, especialmente em períodos de maior estresse ou durante tratamentos de saúde desgastantes.',
      distancia: 'sim',
    },
    indicacoes: [
      'Relaxamento profundo e redução do estresse',
      'Ansiedade e sobrecarga emocional',
      'Dificuldade para dormir',
      'Apoio complementar durante tratamentos médicos intensivos',
      'Cuidados paliativos, como suporte de conforto',
      'Momentos de luto, transição e crise pessoal',
      'Recuperação pós-cirúrgica, como suporte ao conforto',
      'Autoconhecimento e conexão espiritual',
    ],
    limites:
      'O Reiki não é tratamento médico, não diagnostica e não cura doenças. Jamais deve substituir ou atrasar diagnóstico, cirurgia, medicação, quimioterapia ou acompanhamento psiquiátrico e psicológico. É recurso complementar de relaxamento e apoio emocional.',
    faq: [
      { pergunta: 'O Reiki tem comprovação científica?', resposta: 'A evidência é limitada e heterogênea. Alguns estudos sugerem benefício em relaxamento e ansiedade, mas revisões rigorosas apontam baixa qualidade metodológica. É uma prática de baixo risco, com eficácia clínica ainda não estabelecida.' },
      { pergunta: 'Preciso acreditar em energia para receber Reiki?', resposta: 'Não é exigida nenhuma crença específica. A maior parte das pessoas relata relaxamento independentemente de suas convicções.' },
      { pergunta: 'O Reiki substitui tratamento médico ou psicológico?', resposta: 'Não, em nenhuma hipótese. É complementar e deve caminhar junto ao acompanhamento de saúde.' },
      { pergunta: 'É preciso tocar o corpo durante a sessão?', resposta: 'Não necessariamente. Muitas vezes as mãos ficam levemente próximas ao corpo, sem contato direto, especialmente em áreas mais sensíveis.' },
      { pergunta: 'O que é a sintonização?', resposta: 'É o processo de iniciação pelo qual um mestre transmite ao aluno, segundo a tradição, a capacidade de canalizar o Reiki. Em japonês, reiju.' },
      { pergunta: 'O Reiki está disponível no SUS?', resposta: 'Sim. Desde 2017 integra formalmente a lista de práticas da PNPIC, podendo ser ofertado por unidades de saúde que decidam implementá-lo — embora a disponibilidade varie muito entre municípios.' },
      { pergunta: 'Preciso fazer alguma coisa antes da sessão?', resposta: 'Nada obrigatório. Use roupa confortável, evite chegar correndo e, se puder, vá ao banheiro antes — são 45 a 60 minutos deitado. Não há jejum nem restrição alimentar.' },
      { pergunta: 'O Reiki tem contraindicação?', resposta: 'Por não envolver pressão, agulha, substância ou manipulação, não há contraindicação clínica conhecida. O risco real é outro: usar o Reiki para adiar uma consulta, um exame ou um tratamento que você precisa fazer.' },
      { pergunta: 'Grávida pode receber Reiki?', resposta: 'Sim, é uma das práticas mais frequentemente procuradas na gestação justamente por não haver toque com pressão nem estímulo de pontos. Informe a gravidez ao terapeuta, para que a posição na maca seja confortável para você.' },
      { pergunta: 'Criança pode receber Reiki?', resposta: 'Pode, com o consentimento e a presença de quem é responsável, e em sessões geralmente mais curtas. Vale lembrar que qualquer sintoma persistente da criança precisa de avaliação pediátrica — o Reiki não ocupa esse lugar.' },
      { pergunta: 'E se eu não sentir calor nem formigamento?', resposta: 'É absolutamente comum. Boa parte das pessoas relata só um relaxamento discreto, e há quem não note nada além de ter descansado. Sensação forte não é sinal de sessão boa, assim como a ausência dela não é sinal de sessão ruim.' },
      { pergunta: 'O Reiki cura doença?', resposta: 'Não. Ele não cura, não trata e não diagnostica nada. O que os relatos descrevem, e alguns estudos de qualidade limitada sugerem, é alívio de tensão e ansiedade percebida. Isso é diferente de tratar uma doença, e a distinção importa.' },
      { pergunta: 'Como me sinto depois? Posso voltar a trabalhar?', resposta: 'Na maioria dos casos sim, sem qualquer restrição. Os relatos mais comuns são de sonolência, calma e vontade de beber água. Se você sair muito relaxado, evite compromisso que exija pressa logo em seguida.' },
      { pergunta: 'Reiki à distância funciona igual ao presencial?', resposta: 'Dentro da tradição, sim — o sistema prevê a prática à distância desde sua formulação. Fora dela, não há como comparar as duas formas em termos de evidência, porque a eficácia clínica do Reiki em si não está estabelecida. Quem faz online costuma relatar a mesma sensação de descanso.' },
      { pergunta: 'Posso fazer Reiki junto com acupuntura, psicoterapia ou tratamento médico?', resposta: 'Sim, e é assim que ele funciona melhor: ao lado do resto, nunca no lugar. Conte ao terapeuta o que você já faz e não suspenda nenhuma medicação ou consulta por causa das sessões.' },
    ],
    termos: [
      { termo: 'Ki', definicao: 'Energia vital universal, conceito central do Reiki, equivalente ao Qi chinês.' },
      { termo: 'Reiju / sintonização', definicao: 'Processo de iniciação transmitido por um mestre, que habilitaria o aluno a canalizar a energia.' },
      { termo: 'Gassho', definicao: 'Postura de meditação com as palmas unidas diante do peito, praticada antes e depois das sessões.' },
      { termo: 'Usui Shiki Ryoho', definicao: 'Nome do sistema de Reiki tal como sistematizado por Mikao Usui.' },
      { termo: 'Byosen', definicao: 'Percepção, pelas mãos do praticante, de variações de sensação em determinadas regiões do corpo.' },
      { termo: 'Reiki à distância', definicao: 'Modalidade em que a prática é realizada sem a presença física da pessoa, segundo a tradição do sistema.' },
      { termo: 'PNPIC', definicao: 'Política Nacional de Práticas Integrativas e Complementares, do Ministério da Saúde, que inclui o Reiki desde 2017.' },
    ],
    keywords: ['o que é reiki', 'sessão de reiki', 'reiki para ansiedade', 'reiki à distância', 'reiki funciona', 'reiki no SUS', 'benefícios do reiki', 'reiki perto de mim'],
    fontes: [{ titulo: 'Ministério da Saúde — Práticas Integrativas e Complementares', url: 'https://www.gov.br/saude/pt-br/composicao/saps/pics' }],
  },
  {
    slug: 'shiatsu',
    nome: 'Massagem Shiatsu',
    nomeCurto: 'Shiatsu',
    tagline: 'Pressão dos dedos, escuta pelo toque',
    resumo:
      'Terapia manual japonesa em que o terapeuta aplica pressão rítmica com polegares, palmas e cotovelos sobre pontos do corpo. Feita com a pessoa vestida, sem óleos, combinando pressão, alongamentos e mobilizações.',
    destaque: false,
    ordem: 5,
    acento: 'coral',
    icone: 'shiatsu',
    origem:
      'O Shiatsu — de shi (dedo) e atsu (pressão) — nasce das práticas manuais japonesas como o Anma, somadas a princípios da Medicina Tradicional Chinesa. Foi sistematizado no início do século XX por Tokujiro Namikoshi (1905–2000), responsável pelo reconhecimento oficial da técnica pelo Ministério da Saúde japonês em 1964, e ampliado por Shizuto Masunaga (1925–1981), criador do Shiatsu Zen. Chegou ao Brasil nas décadas de 1970 e 1980.',
    oQueE: [
      'O Shiatsu é uma terapia manual japonesa em que o terapeuta aplica pressão rítmica e sustentada — principalmente com os polegares, mas também com palmas, cotovelos e joelhos — sobre pontos específicos, seguindo trajetos que a tradição chama de meridianos. Não usa óleos e é realizado com a pessoa vestida, sobre futon ou maca.',
      'Na tradição japonesa, o objetivo é favorecer o reequilíbrio do fluxo de energia vital, aliviar tensões musculares e promover relaxamento profundo. É uma prática que valoriza o toque presente: o terapeuta "escuta" com as mãos as áreas de tensão antes de decidir onde e como aplicar a pressão.',
    ],
    comoFunciona: [
      'Segundo a tradição, uma energia vital chamada Ki circula pelo corpo por canais chamados meridianos; quando esse fluxo estaria bloqueado ou estagnado, surgiriam desconfortos físicos e emocionais.',
      'A pressão nos tsubos — pontos ao longo dos meridianos — teria a função de estimular, tonificar ou dispersar esse fluxo.',
      'A avaliação do hara, a região abdominal, orienta a escolha das áreas a trabalhar.',
    ],
    evidencia:
      'O nível de evidência é baixo a moderado. Há estudos, inclusive brasileiros, sugerindo benefício na redução de dor, ansiedade e melhora do sono, mas com amostras pequenas e metodologia heterogênea. Os efeitos mais consistentemente relatados — relaxamento e redução da tensão percebida — são compatíveis com os de qualquer toque terapêutico cuidadoso. O Shiatsu não consta entre as práticas da PNPIC em nível federal.',
    sessao: {
      duracao: '40 a 60 minutos',
      formato: 'Com roupas leves e confortáveis, sobre futon no chão ou maca. Sem óleos.',
      sensacao: 'Pressão firme e progressiva, por vezes com desconforto pontual e passageiro em áreas de maior tensão, seguida de relaxamento e leveza.',
      frequencia: 'De uma sessão pontual a ciclos de 4 a 8 sessões, semanais ou quinzenais, para queixas mais persistentes.',
      distancia: 'nao',
    },
    indicacoes: [
      'Tensão muscular e dores nas costas, pescoço e ombros',
      'Estresse e ansiedade do dia a dia',
      'Dificuldade para dormir',
      'Cansaço e fadiga',
      'Dores de cabeça tensionais',
      'Sobrecarga emocional',
      'Consciência corporal e postura',
      'Momentos de autocuidado e desaceleração',
    ],
    limites:
      'O Shiatsu não é procedimento médico, não diagnostica doenças e não substitui consultas, exames ou tratamentos prescritos. Há contraindicações: gestação de risco ou primeiro trimestre sem liberação médica, fraturas recentes, trombose, osteoporose grave, febre e infecções agudas, áreas com câncer ativo ou pós-cirúrgico recente, distúrbios de coagulação e uso de anticoagulantes. Informe sempre o terapeuta sobre sua condição de saúde.',
    faq: [
      { pergunta: 'O Shiatsu dói?', resposta: 'Pode haver desconforto pontual em áreas de tensão mais intensa, mas a pressão é sempre ajustada à sua tolerância. Não deve haver dor incapacitante.' },
      { pergunta: 'Preciso tirar a roupa?', resposta: 'Não. O Shiatsu é feito com a pessoa vestida, de preferência com roupas leves e confortáveis.' },
      { pergunta: 'Shiatsu é a mesma coisa que acupuntura?', resposta: 'Não. Compartilham a base teórica dos meridianos, mas a acupuntura usa agulhas e o Shiatsu usa exclusivamente pressão manual, alongamentos e mobilizações.' },
      { pergunta: 'Gestantes podem fazer Shiatsu?', resposta: 'Em gestações sem complicações e com liberação médica, existem protocolos adaptados que evitam pontos contraindicados. Informe a gestação antes da sessão.' },
      { pergunta: 'Quantas sessões para sentir efeito?', resposta: 'Muita gente relata relaxamento já na primeira. Para queixas persistentes, costuma-se recomendar um ciclo de sessões com frequência regular.' },
      { pergunta: 'Qual a diferença entre Shiatsu e massagem relaxante?', resposta: 'A massagem relaxante trabalha o deslizamento sobre a musculatura, geralmente com óleo. O Shiatsu trabalha pressão sustentada em pontos, com a pessoa vestida, seguindo os trajetos dos meridianos.' },
      { pergunta: 'O que devo vestir para a sessão?', resposta: 'Roupa leve, de tecido que estique — legging, moletom fino, camiseta de algodão. Evite jeans, cinto, saia justa e acessórios que apertem. Meias são bem-vindas, e brincos e relógio costumam sair antes de começar.' },
      { pergunta: 'Posso comer antes do Shiatsu?', resposta: 'Pode, mas evite refeição pesada nas duas horas anteriores. Há trabalho de pressão sobre o abdome e posições deitado de bruços, e estômago cheio deixa isso desconfortável. Um lanche leve não atrapalha.' },
      { pergunta: 'É normal ficar dolorido no dia seguinte?', resposta: 'Um leve dolorimento em áreas muito tensas pode aparecer e costuma passar em um ou dois dias, parecido com o de um alongamento intenso. Beba água e evite esforço pesado logo depois. Dor forte ou que aumenta não é esperada — avise o terapeuta.' },
      { pergunta: 'Posso fazer Shiatsu se tomo anticoagulante?', resposta: 'Anticoagulantes e distúrbios de coagulação exigem cautela, porque a pressão firme favorece hematomas. Fale com seu médico antes e informe o terapeuta: em geral se opta por pressão mais leve ou por outra abordagem.' },
      { pergunta: 'Shiatsu resolve hérnia de disco?', resposta: 'Não. Hérnia de disco é diagnóstico médico e pede avaliação ortopédica e, muitas vezes, fisioterapia. O Shiatsu pode, no máximo, ajudar na tensão muscular ao redor, e só depois de liberação de quem acompanha o caso.' },
      { pergunta: 'O Shiatsu está no SUS?', resposta: 'Não nominalmente. A lista oficial da PNPIC tem 29 práticas e o Shiatsu não é uma delas. O que consta desde 2006 é a Medicina Tradicional Chinesa – acupuntura, campo do qual o Shiatsu é vizinho por compartilhar a teoria dos meridianos.' },
      { pergunta: 'Dá para fazer Shiatsu à distância?', resposta: 'Não. É uma terapia de toque e depende da presença física. O que pode ser feito remotamente é orientação de Do-In, o conjunto de automassagens que a própria pessoa aplica, mas isso é outra coisa.' },
      { pergunta: 'Posso combinar Shiatsu com acupuntura ou fisioterapia?', resposta: 'Sim, são abordagens compatíveis e muita gente faz as duas. Só evite marcar Shiatsu e acupuntura no mesmo dia, para não sobrecarregar, e conte ao fisioterapeuta o que está fazendo.' },
      { pergunta: 'Quem pode aplicar Shiatsu?', resposta: 'O Shiatsu não é profissão regulamentada no Brasil, o que torna a formação do profissional a informação mais importante. Pergunte onde ele estudou, por quantas horas e em qual linha — Namikoshi, Zen ou outra.' },
    ],
    termos: [
      { termo: 'Ki', definicao: 'Na tradição japonesa, a energia vital que circularia pelo corpo — equivalente ao Qi chinês.' },
      { termo: 'Meridianos', definicao: 'Canais pelos quais, segundo a Medicina Tradicional Chinesa, o Ki circula conectando órgãos e regiões.' },
      { termo: 'Tsubo', definicao: 'Ponto específico de pressão ao longo de um meridiano, correspondente aos pontos de acupuntura.' },
      { termo: 'Hara', definicao: 'A região abdominal, considerada na tradição japonesa o centro energético e físico do corpo.' },
      { termo: 'Kyo e Jitsu', definicao: 'Conceitos de vazio (kyo) e excesso (jitsu) de energia numa região, usados para orientar a pressão.' },
      { termo: 'Anma', definicao: 'Massagem tradicional japonesa mais antiga, precursora do Shiatsu.' },
      { termo: 'Shiatsu Namikoshi', definicao: 'Estilo criado por Tokujiro Namikoshi, com abordagem mais próxima da fisiologia ocidental.' },
      { termo: 'Shiatsu Zen', definicao: 'Estilo desenvolvido por Shizuto Masunaga, com ênfase ampliada nos meridianos e na dimensão psicoemocional.' },
      { termo: 'Do-In', definicao: 'Conjunto de automassagens e alongamentos inspirados nos mesmos princípios, praticados pela própria pessoa.' },
    ],
    keywords: ['o que é shiatsu', 'massagem shiatsu para que serve', 'shiatsu para dor nas costas', 'shiatsu para ansiedade', 'benefícios do shiatsu', 'shiatsu contraindicações', 'diferença entre shiatsu e massagem', 'terapeuta shiatsu'],
    fontes: [{ titulo: 'Ministério da Saúde — Práticas Integrativas e Complementares', url: 'https://www.gov.br/saude/pt-br/composicao/saps/pics' }],
  },
]

const grupo3: Terapia[] = [
  {
    slug: 'acupuntura-sistemica',
    nome: 'Acupuntura Sistêmica',
    nomeCurto: 'Acupuntura',
    tagline: 'Pontos por todo o corpo, leitura do todo',
    resumo:
      'Técnica da Medicina Tradicional Chinesa com mais de dois mil anos, que utiliza agulhas finas e descartáveis em pontos distribuídos por todo o corpo. É a prática integrativa com maior corpo de evidência científica, sobretudo no manejo da dor.',
    destaque: false,
    ordem: 6,
    acento: 'agua',
    icone: 'acupuntura',
    origem:
      'A acupuntura é uma das práticas mais antigas da Medicina Tradicional Chinesa, sistematizada sobretudo no clássico Huangdi Neijing. Não tem um criador único: é fruto de uma tradição médica coletiva desenvolvida ao longo de séculos. Chegou ao Ocidente em ondas sucessivas e se difundiu de forma decisiva a partir da década de 1970. No Brasil, é especialidade médica reconhecida pelo Conselho Federal de Medicina desde 1995 e integra a PNPIC desde 2006.',
    oQueE: [
      'A acupuntura sistêmica consiste na inserção de agulhas finas, estéreis e descartáveis em pontos específicos distribuídos por todo o corpo — membros, tronco, face e couro cabeludo. O termo "sistêmica" a distingue da auriculoterapia e de outras variantes localizadas: aqui o corpo é lido como um todo.',
      'Na tradição chinesa, cada ponto está associado a um meridiano, um dos canais pelos quais a energia vital circularia conectando órgãos, tecidos e funções. Antes de aplicar as agulhas, faz-se uma avaliação segundo os princípios da Medicina Tradicional Chinesa — observação da língua, palpação do pulso, escuta dos sintomas — para identificar padrões de desequilíbrio e escolher os pontos de cada sessão.',
    ],
    comoFunciona: [
      'Segundo a tradição, o mal-estar resultaria de um desequilíbrio no fluxo do Qi pelos meridianos ou entre as forças complementares Yin e Yang.',
      'A inserção das agulhas teria o papel de desobstruir, tonificar ou dispersar esse fluxo, restabelecendo o equilíbrio.',
      'A escolha dos pontos varia a cada sessão, conforme a leitura do momento da pessoa.',
    ],
    evidencia:
      'A acupuntura é uma das práticas integrativas mais estudadas, com milhares de ensaios clínicos e revisões sistemáticas. A evidência é mais consistente no manejo da dor — lombalgia crônica, cervicalgia, enxaqueca, cefaleia tensional, osteoartrite de joelho —, com recomendação em diretrizes clínicas internacionais. Para outras finalidades a evidência é mais heterogênea. Um debate honesto e relevante: estudos que comparam acupuntura "verdadeira" com acupuntura simulada costumam mostrar diferenças pequenas, o que sugere que parte do efeito venha de componentes inespecíficos. Ainda assim, o benefício percebido em dor crônica é real e mensurável em muitos estudos.',
    sessao: {
      duracao: '30 a 60 minutos',
      formato: 'Presencial, com avaliação inicial segundo a Medicina Tradicional Chinesa e permanência das agulhas por 20 a 40 minutos.',
      sensacao: 'Uma picada fina e rápida na inserção, seguida por vezes da sensação chamada De Qi — peso, formigamento ou leve distensão no ponto — e, na maioria dos relatos, relaxamento profundo. Muita gente adormece durante a sessão.',
      frequencia: 'De sessões pontuais para alívio agudo a ciclos de 6 a 12 sessões, semanais ou quinzenais, em quadros crônicos.',
      distancia: 'nao',
    },
    indicacoes: [
      'Dores crônicas: lombalgia, cervicalgia, dores articulares',
      'Enxaqueca e cefaleia tensional',
      'Estresse e ansiedade',
      'Insônia e distúrbios do sono',
      'Sintomas da menopausa',
      'Recuperação de lesões, como complemento',
      'Desconfortos digestivos funcionais',
      'Fadiga e baixa energia',
    ],
    limites:
      'A acupuntura não diagnostica nem trata doenças graves isoladamente e não substitui avaliação médica, exames ou tratamentos convencionais. A aplicação de agulhas é procedimento invasivo, reservado por lei a profissionais de saúde regulamentados e habilitados. Há contraindicações: distúrbios de coagulação, uso de anticoagulantes, gestação (certos pontos), infecções na região a agulhar, jejum prolongado e imunossupressão exigem cautela ou avaliação prévia.',
    faq: [
      { pergunta: 'Acupuntura dói?', resposta: 'As agulhas são muito mais finas que as de injeção. A maioria das pessoas sente apenas uma picada leve e passageira, seguida de peso ou formigamento no ponto, e depois relaxamento.' },
      { pergunta: 'Quantas sessões são necessárias?', resposta: 'Depende do caso. Dores agudas podem melhorar em poucas sessões; quadros crônicos costumam pedir ciclos de 6 a 12 sessões, com reavaliação periódica.' },
      { pergunta: 'A acupuntura é reconhecida pela medicina?', resposta: 'Sim. No Brasil é especialidade médica reconhecida pelo CFM desde 1995 e integra a PNPIC do SUS desde 2006, com respaldo científico mais consistente no manejo da dor.' },
      { pergunta: 'Quem pode aplicar acupuntura?', resposta: 'A aplicação de agulhas é procedimento invasivo, reservado a profissionais de saúde regulamentados e capacitados conforme seus conselhos profissionais.' },
      { pergunta: 'Existe algum risco?', resposta: 'Com profissional qualificado e material estéril e descartável, os riscos são baixos. Os efeitos adversos mais comuns são pequenos hematomas ou dor leve no local.' },
      { pergunta: 'É a mesma coisa que auriculoterapia?', resposta: 'Não. A acupuntura sistêmica usa pontos por todo o corpo; a auriculoterapia trabalha apenas pontos na orelha. As duas podem ser combinadas.' },
      { pergunta: 'Posso comer antes da acupuntura?', resposta: 'Sim, e é melhor que você não vá em jejum. Jejum prolongado aumenta a chance de tontura ou mal-estar durante a sessão. Faça uma refeição leve uma ou duas horas antes, sem exagero.' },
      { pergunta: 'O que vestir para a sessão?', resposta: 'Roupa larga e fácil de dobrar, que permita expor braços e pernas até o joelho e a região lombar. Peças justas nos punhos e tornozelos atrapalham, porque muitos pontos importantes ficam ali.' },
      { pergunta: 'Como me sinto depois? Posso dirigir?', resposta: 'A maioria sai relaxada e apta a seguir o dia normalmente. Sonolência, leve tontura ao levantar e vontade de dormir mais cedo são relatos comuns nas primeiras sessões. Se você se sentir muito mole, espere alguns minutos sentado antes de sair dirigindo.' },
      { pergunta: 'Acupuntura funciona para enxaqueca?', resposta: 'É a indicação com melhor respaldo. A revisão Cochrane de Linde e colaboradores indica certeza moderada de benefício na prevenção de enxaqueca, com pelo menos seis sessões. Isso vale para prevenção de enxaqueca — não é possível estender esse achado a outras condições.' },
      { pergunta: 'Posso fazer acupuntura grávida?', resposta: 'Alguns pontos são contraindicados na gestação e outros exigem cautela conforme o trimestre. Informe a gravidez antes de qualquer sessão e converse com quem acompanha o pré-natal. Com essa conversa feita e um profissional habilitado, existem protocolos adaptados.' },
      { pergunta: 'Posso fazer acupuntura tomando meus remédios?', resposta: 'Sim, não há interação. Conte ao profissional tudo o que você usa, sobretudo anticoagulantes e imunossupressores, porque isso muda a conduta. E nenhuma medicação deve ser reduzida ou suspensa por causa das sessões — só quem prescreveu pode mexer nisso.' },
      { pergunta: 'A acupuntura substitui o remédio para dor?', resposta: 'Não, e não deve ser apresentada assim. Ela é usada como recurso complementar no manejo da dor, com evidência mais consistente em quadros crônicos. Qualquer redução de medicação é decisão do médico que acompanha você, tomada com base na sua evolução.' },
      { pergunta: 'As agulhas são reaproveitadas?', resposta: 'Não. As agulhas são estéreis, de uso único e descartadas em recipiente próprio na sua frente. Se em algum lugar isso não estiver claro, pergunte antes de começar — você tem todo o direito de ver a embalagem sendo aberta.' },
      { pergunta: 'Existe acupuntura à distância?', resposta: 'Não. A inserção de agulhas exige presença física e profissional habilitado. Consulta online serve para avaliação e orientação, mas a aplicação em si é sempre presencial.' },
    ],
    termos: [
      { termo: 'Qi', definicao: 'Energia vital que, segundo a Medicina Tradicional Chinesa, circula pelo corpo e sustenta suas funções.' },
      { termo: 'Meridianos', definicao: 'Canais pelos quais o Qi circularia, conectando pontos de acupuntura a órgãos e funções.' },
      { termo: 'Yin e Yang', definicao: 'Princípio chinês de forças complementares e opostas, cujo equilíbrio seria a base da saúde.' },
      { termo: 'De Qi', definicao: 'Sensação de peso, formigamento ou distensão no ponto quando a agulha é corretamente inserida — sinal de estímulo eficaz na tradição.' },
      { termo: 'Zang-Fu', definicao: 'Teoria dos órgãos internos na MTC, que associa cada órgão a funções energéticas e emocionais.' },
      { termo: 'Eletroacupuntura', definicao: 'Variante em que se aplica leve corrente elétrica entre pares de agulhas para intensificar o estímulo.' },
      { termo: 'Moxabustão', definicao: 'Técnica complementar que usa o calor da combustão da Artemisia próxima aos pontos, para aquecer e tonificar.' },
      { termo: 'Diagnóstico pelo pulso e pela língua', definicao: 'Métodos tradicionais de avaliação usados na MTC antes de definir os pontos a tratar.' },
      { termo: 'Huangdi Neijing', definicao: 'Clássico Interno do Imperador Amarelo, texto fundador da Medicina Tradicional Chinesa.' },
    ],
    keywords: ['o que é acupuntura sistêmica', 'acupuntura para dor nas costas', 'acupuntura para ansiedade', 'quantas sessões de acupuntura', 'acupuntura dói', 'acupuntura para enxaqueca', 'acupuntura sistêmica x auricular'],
    fontes: [{ titulo: 'Ministério da Saúde — Práticas Integrativas e Complementares', url: 'https://www.gov.br/saude/pt-br/composicao/saps/pics' }],
  },
  {
    slug: 'auriculoterapia',
    nome: 'Auriculoterapia',
    nomeCurto: 'Auriculoterapia',
    tagline: 'A orelha como mapa do corpo',
    resumo:
      'Estimulação de pontos específicos no pavilhão auricular com sementes, esferas ou agulhas semipermanentes. Pouco invasiva, rápida e amplamente utilizada no SUS, sobretudo no manejo da ansiedade e da dor.',
    destaque: false,
    ordem: 7,
    acento: 'coral',
    icone: 'auriculoterapia',
    origem:
      'A auriculoterapia tem duas raízes. A chinesa antiga: textos como o Huangdi Neijing já mencionavam a relação entre a orelha e os órgãos internos. E a francesa moderna: o médico Paul Nogier (1908–1996), de Lyon, sistematizou a técnica a partir de 1956, desenvolvendo o mapa dos pontos auriculares — o "homúnculo invertido", em que a orelha representa um feto de cabeça para baixo. Seus estudos foram levados de volta à China e ali expandidos, num diálogo de mão dupla entre Oriente e Ocidente.',
    oQueE: [
      'A auriculoterapia consiste na estimulação de pontos específicos do pavilhão auricular — a orelha externa — por meio de sementes, esferas metálicas fixadas com micropore, agulhas semipermanentes, laser ou pressão manual. A ideia central é que a orelha funcionaria como um microssistema: um mapa reduzido de todo o corpo, no qual cada região, órgão ou função encontraria correspondência em um ponto.',
      'Por ser pouco invasiva, rápida de aplicar e não exigir que a pessoa se dispa, tornou-se uma das práticas integrativas mais utilizadas na saúde pública brasileira — isolada ou como complemento à acupuntura sistêmica, especialmente no manejo da ansiedade, dor crônica, insônia e apoio à cessação do tabagismo.',
    ],
    comoFunciona: [
      'Segundo a tradição, a estimulação dos pontos auriculares atuaria sobre o fluxo de energia e sobre os órgãos e sistemas correspondentes.',
      'No modelo de Nogier, a orelha reflete todo o corpo como um feto invertido; na tradição chinesa, os pontos auriculares se conectam à rede mais ampla dos meridianos.',
      'Após a aplicação, é comum orientar a pessoa a pressionar os pontos algumas vezes ao dia, para reforçar o estímulo ao longo da semana.',
    ],
    evidencia:
      'A auriculoterapia é uma das práticas integrativas com volume relativamente maior de estudos clínicos, incluindo revisões sistemáticas indexadas. Há evidência de qualidade moderada sugerindo benefício na redução de ansiedade, estresse e sintomas depressivos leves a moderados, no manejo auxiliar da dor e no apoio à cessação do tabagismo. Ainda assim, persistem limitações metodológicas — amostras pequenas, dificuldade de cegamento, protocolos heterogêneos —, o que a posiciona como recurso complementar com evidência favorável, mas não conclusiva.',
    sessao: {
      duracao: '20 a 40 minutos',
      formato: 'Presencial, com breve anamnese e aplicação de sementes, esferas ou agulhas semipermanentes na orelha.',
      sensacao: 'Leve pressão ou pontada rápida na aplicação, seguida de relaxamento. As sementes ou agulhas permanecem de 3 a 7 dias.',
      frequencia: 'Sessões semanais ou quinzenais, em ciclos de 4 a 10 sessões conforme o objetivo.',
      distancia: 'nao',
    },
    indicacoes: [
      'Ansiedade e sintomas de estresse',
      'Insônia e distúrbios do sono',
      'Apoio à cessação do tabagismo',
      'Compulsão alimentar e apoio à reeducação alimentar',
      'Dores crônicas: enxaqueca, lombar, articulares',
      'Tensão diante de exames e situações pontuais',
      'Enjoos e náuseas',
      'Sintomas do ciclo menstrual e da menopausa',
    ],
    limites:
      'A auriculoterapia não diagnostica doenças, não substitui exames nem tratamentos prescritos, e não deve ser apresentada como cura de dependências químicas, transtornos psiquiátricos ou doenças crônicas. Contraindicações: infecções ou lesões na orelha, alergia a metais ou ao adesivo, gestação (certos pontos), distúrbios importantes de coagulação. A aplicação de agulhas, por ser invasiva, é reservada a profissionais de saúde regulamentados.',
    faq: [
      { pergunta: 'A auriculoterapia dói?', resposta: 'A aplicação costuma causar apenas uma sensação rápida de pressão ou beliscão leve, seguida de conforto. Não é um procedimento doloroso na maioria dos relatos.' },
      { pergunta: 'Por quanto tempo as sementes ficam na orelha?', resposta: 'Em geral de 3 a 7 dias. É importante manter a região limpa e seca nesse período.' },
      { pergunta: 'Auriculoterapia ajuda a emagrecer?', resposta: 'Pode ser apoio complementar dentro de um processo de reeducação alimentar, ajudando no manejo da compulsão e da ansiedade. Não emagrece por si só, nem substitui orientação nutricional.' },
      { pergunta: 'Serve para parar de fumar?', resposta: 'É usada como apoio complementar em programas de cessação do tabagismo, inclusive no SUS, geralmente associada a acompanhamento médico ou psicológico.' },
      { pergunta: 'Posso fazer grávida?', resposta: 'Alguns pontos são contraindicados na gestação. É indispensável informar a gravidez antes da sessão.' },
      { pergunta: 'Qual a diferença para a acupuntura sistêmica?', resposta: 'A auriculoterapia trabalha exclusivamente pontos na orelha; a acupuntura sistêmica usa pontos por todo o corpo. Muitas vezes as duas são combinadas.' },
      { pergunta: 'Posso tomar banho e lavar o cabelo com as sementinhas?', resposta: 'Pode tomar banho normalmente, evitando molhar a orelha em excesso e secando bem depois, com cuidado. Piscina, mar e sauna soltam o adesivo mais rápido. Manter a região limpa e seca é a principal orientação do período.' },
      { pergunta: 'E se a sementinha cair antes do tempo?', resposta: 'Acontece com frequência, sobretudo em quem tem pele oleosa ou dorme de lado, e não é problema. Não tente recolocar em casa, porque o ponto exato importa. Anote quando caiu e conte na sessão seguinte.' },
      { pergunta: 'Posso dormir de lado com as sementes?', resposta: 'Pode, e é o que a maioria faz. Pode haver um incômodo nos primeiros dias sobre o lado aplicado, que costuma diminuir. Se estiver doendo de verdade ou incomodando o sono, retire e avise o terapeuta.' },
      { pergunta: 'Quem tem alergia a esparadrapo pode fazer?', resposta: 'Avise antes. Alergia a metais ou a adesivo é contraindicação relativa, e existem alternativas — micropore hipoalergênico, esferas de material diferente ou apenas pressão manual. Se aparecer vermelhidão, coceira ou irritação, retire e comunique o terapeuta.' },
      { pergunta: 'A auriculoterapia cura ansiedade?', resposta: 'Não. Ela é um recurso complementar, e a evidência disponível, ainda que favorável em alguns estudos, não é conclusiva. Ansiedade que atrapalha o sono, o trabalho ou a vida cotidiana pede avaliação com profissional de saúde mental. As duas coisas podem caminhar juntas.' },
      { pergunta: 'Criança pode fazer auriculoterapia?', resposta: 'Com consentimento e presença de quem é responsável, e em geral só com sementes, sem agulha. A orelha infantil é pequena e a pele mais sensível, então o tempo de permanência costuma ser menor. Sintoma persistente em criança precisa de avaliação pediátrica.' },
      { pergunta: 'A auriculoterapia está no SUS?', resposta: 'Ela não tem entrada própria na lista da PNPIC — é uma técnica dentro da Medicina Tradicional Chinesa, essa sim na política desde 2006. O Ministério da Saúde mantém formação nacional de auriculoterapia para a Atenção Primária, e ela é muito usada na rede. Reconhecimento em política pública, porém, não é o mesmo que comprovação de eficácia.' },
      { pergunta: 'Faz nas duas orelhas ao mesmo tempo?', resposta: 'Costuma-se aplicar em uma orelha por sessão, alternando na seguinte, para não sobrecarregar e para dar descanso à pele. Alguns protocolos usam as duas. Isso varia com a abordagem do profissional e com o seu caso.' },
    ],
    termos: [
      { termo: 'Pavilhão auricular', definicao: 'A parte externa e visível da orelha, onde ficam os pontos trabalhados.' },
      { termo: 'Homúnculo invertido', definicao: 'Modelo de Paul Nogier que projeta o corpo humano de cabeça para baixo sobre a orelha.' },
      { termo: 'Microssistema', definicao: 'Conceito segundo o qual uma parte do corpo — orelha, mão, pé — contém a representação do organismo inteiro.' },
      { termo: 'Protocolo NADA', definicao: 'Protocolo padronizado de cinco pontos auriculares, criado nos EUA e amplamente usado no apoio a dependências químicas.' },
      { termo: 'Vaccaria', definicao: 'Pequenas sementes fixadas com adesivo sobre os pontos auriculares, alternativa não invasiva às agulhas.' },
      { termo: 'Agulha semipermanente', definicao: 'Agulha muito fina e curta, fixada na orelha por alguns dias para estímulo contínuo.' },
      { termo: 'Auriculomapa', definicao: 'Representação gráfica dos pontos auriculares e suas correspondências corporais.' },
    ],
    keywords: ['o que é auriculoterapia', 'auriculoterapia para ansiedade', 'auriculoterapia para emagrecer', 'auriculoterapia sementes', 'auriculoterapia para parar de fumar', 'auriculoterapia contraindicações', 'auriculoterapia perto de mim'],
    fontes: [{ titulo: 'Ministério da Saúde — Práticas Integrativas e Complementares', url: 'https://www.gov.br/saude/pt-br/composicao/saps/pics' }],
  },
  {
    slug: 'seitai',
    nome: 'Seitai',
    nomeCurto: 'Seitai',
    tagline: 'Organizar o corpo',
    resumo:
      'Terapia manual japonesa de reequilíbrio postural e estrutural. O nome significa literalmente "organizar o corpo": por manobras manuais, busca-se criar condições para que o corpo reencontre seu próprio equilíbrio.',
    destaque: false,
    ordem: 8,
    acento: 'violeta',
    icone: 'seitai',
    origem:
      'O Seitai (整体) tem raízes em técnicas manuais japonesas antigas e foi sistematizado em sua forma moderna por Haruchika Noguchi (1911–1976). Dele vêm dois conceitos centrais: o Taiheki, tipologia constitucional do corpo, e o Katsugen Undo, o movimento regenerador espontâneo. Foi levado ao Ocidente por discípulos como Itsuo Tsuda. No Brasil convivem a linha mais fiel à tradição de Noguchi e versões comerciais adaptadas.',
    oQueE: [
      'O Seitai é uma terapia manual japonesa voltada ao reequilíbrio postural e estrutural. Por manobras manuais — e, em algumas linhas, com instrumentos específicos —, o terapeuta ajuda o corpo a se reorganizar, aliviando tensões, dores e compensações posturais acumuladas.',
      'Um princípio central da tradição de Noguchi é a confiança na capacidade natural do corpo de se regular. Mais do que impor uma correção externa, o Seitai busca criar condições para que o corpo reencontre seu equilíbrio.',
    ],
    comoFunciona: [
      'O corpo é lido como uma estrutura interconectada: um desequilíbrio numa região pode gerar compensações e dores em pontos distantes.',
      'O terapeuta avalia padrões posturais e usa manobras manuais para estimular o realinhamento de articulações, músculos e tendões.',
      'Na vertente mais próxima de Noguchi, o Katsugen Undo propõe que, ao suspender o controle consciente, o corpo expressa movimentos espontâneos de função regeneradora.',
    ],
    evidencia:
      'Os mecanismos específicos propostos pelo Seitai — autorregulação, katsugen undo — não têm comprovação em fisiologia médica convencional, e não há estudos controlados que os validem. Parte do alívio relatado é compatível com o que já se sabe sobre terapias manuais em geral, o que não constitui validação científica do Seitai em si.',
    sessao: {
      duracao: 'Cerca de 40 a 60 minutos',
      formato: 'Presencial, com a pessoa vestida, deitada em maca. Manobras manuais suaves, sem manipulações bruscas.',
      sensacao: 'Indolor e não invasivo. Relaxamento profundo, alívio de tensões e, em muitos relatos, bem-estar emocional.',
      frequencia: 'Costuma-se propor um ciclo inicial de quatro sessões, seguido de manutenção mensal.',
      distancia: 'nao',
    },
    indicacoes: [
      'Dores crônicas nas costas, pescoço e ombros',
      'Dores agudas por esforço ou má postura',
      'Desalinhamento postural percebido',
      'Tensão muscular ligada ao estresse',
      'Rigidez corporal',
      'Recuperação após esforços intensos',
      'Relaxamento profundo',
      'Interesse em práticas corporais orientais',
    ],
    limites:
      'O Seitai não é fisioterapia, quiropraxia nem procedimento médico regulamentado, e não substitui avaliação médica, ortopédica ou fisioterapêutica — especialmente em dores persistentes, lesões, hérnias de disco, fraturas ou doenças estruturais. Pessoas com condições ósseas, articulares ou neurológicas devem consultar o médico antes e informar o terapeuta.',
    faq: [
      { pergunta: 'O Seitai tem comprovação científica?', resposta: 'Os mecanismos específicos da tradição não têm comprovação própria. Parte do alívio é compatível com o efeito de terapias manuais em geral, mas isso não valida cientificamente o Seitai em si.' },
      { pergunta: 'Dói fazer uma sessão?', resposta: 'Não. É descrita como indolor e não invasiva, sem manipulações bruscas.' },
      { pergunta: 'Quantas sessões são recomendadas?', resposta: 'Costuma-se propor um ciclo inicial de quatro sessões, seguido de manutenção mensal conforme a necessidade.' },
      { pergunta: 'Qual a diferença entre Seitai e quiropraxia?', resposta: 'A quiropraxia é uma profissão regulamentada com técnicas próprias de ajuste articular. O Seitai é uma tradição japonesa de terapia manual, com princípios e manobras distintos.' },
      { pergunta: 'Pode ser feito online?', resposta: 'Não. O Seitai é essencialmente presencial e manual.' },
      { pergunta: 'Substitui fisioterapia ou tratamento ortopédico?', resposta: 'Não. É complementar e não deve atrasar avaliação e tratamento adequados.' },
      { pergunta: 'O que devo vestir?', resposta: 'Roupa confortável que permita movimento — legging, moletom leve, camiseta de algodão. Você permanece vestido durante toda a sessão. Cinto, jeans rígido e acessórios atrapalham as manobras.' },
      { pergunta: 'Tem estalo, como na quiropraxia?', resposta: 'Não é o que caracteriza o Seitai. As manobras são suaves e não dependem de manipulação brusca ou de ajuste com estalo. Se um profissional propuser esse tipo de manobra, pergunte qual é a formação dele para fazê-la.' },
      { pergunta: 'Como me sinto no dia seguinte?', resposta: 'Os relatos mais comuns são de leveza, sono mais profundo e alívio de tensão. Algumas pessoas descrevem um cansaço leve nas primeiras horas. Beba água e evite esforço pesado no mesmo dia.' },
      { pergunta: 'O Seitai tem contraindicação?', resposta: 'Sim. Fraturas recentes, osteoporose importante, inflamação aguda, febre, trombose, uso de anticoagulante e quadros neurológicos exigem avaliação médica antes. Informe sempre o terapeuta sobre cirurgias, lesões e diagnósticos que você tem.' },
      { pergunta: 'O Seitai corrige escoliose ou hérnia de disco?', resposta: 'Não. Escoliose e hérnia de disco são diagnósticos médicos e pedem acompanhamento ortopédico e fisioterapêutico. O Seitai não reverte alteração estrutural, e apresentá-lo assim seria falso. Ele pode, no máximo, oferecer alívio de tensão em torno da área.' },
      { pergunta: 'O Seitai está no SUS?', resposta: 'Não. A lista oficial da PNPIC tem 29 práticas e o Seitai não é uma delas. Também há praticamente nenhuma literatura científica indexada sobre a técnica — ela se sustenta como tradição japonesa e experiência prática, e é honesto dizer isso.' },
      { pergunta: 'Posso fazer com dor aguda ou depois de uma lesão?', resposta: 'Dor aguda que apareceu de repente, depois de queda, torção ou acidente, precisa primeiro de avaliação médica. Depois do diagnóstico e com liberação de quem acompanha, o Seitai pode entrar como cuidado complementar.' },
      { pergunta: 'Posso combinar com fisioterapia, acupuntura ou musculação?', resposta: 'Sim, são compatíveis. Só conte a cada profissional o que você está fazendo, e evite marcar duas terapias manuais no mesmo dia — o corpo pede um intervalo entre elas.' },
      { pergunta: 'Quem pode aplicar Seitai?', resposta: 'Não é profissão regulamentada no Brasil, e por isso a formação do profissional é a informação que importa. Pergunte onde ele estudou, quanto tempo durou o curso e se a linha segue a tradição de Noguchi ou uma versão adaptada.' },
    ],
    termos: [
      { termo: 'Seitai (整体)', definicao: 'Literalmente "organizar o corpo"; terapia manual japonesa de reequilíbrio postural.' },
      { termo: 'Haruchika Noguchi', definicao: 'Sistematizador do Seitai moderno (1911–1976), autor dos conceitos de Taiheki e Katsugen Undo.' },
      { termo: 'Taiheki', definicao: 'Tipologia das tendências constitucionais do corpo, associadas na tradição à coluna lombar.' },
      { termo: 'Katsugen Undo (活元運動)', definicao: 'Movimento regenerador espontâneo: prática em que, suspendendo o controle consciente, o corpo se move por si.' },
      { termo: 'Itsuo Tsuda', definicao: 'Discípulo de Noguchi responsável por difundir o Seitai na Europa.' },
      { termo: 'Autorregulação corporal', definicao: 'Princípio central da tradição: a confiança na capacidade natural do corpo de reencontrar seu equilíbrio.' },
    ],
    keywords: ['seitai o que é', 'terapia manual japonesa', 'seitai dor nas costas', 'seitai realinhamento postural', 'haruchika noguchi seitai', 'katsugen undo', 'sessão de seitai'],
    fontes: [{ titulo: 'Sei-Tai, Taiheki and Katsugen Undo — TraditionalBodywork', url: 'https://www.traditionalbodywork.com/seitai-therapy-and-taiheki-haruchika-noguchi/' }],
  },
]

export const terapias: Terapia[] = [...grupo1, ...grupo2, ...grupo3].sort((a, b) => a.ordem - b.ordem)

export const terapiasDestaque = terapias.filter((t) => t.destaque)

export function getTerapia(slug: string): Terapia | undefined {
  return terapias.find((t) => t.slug === slug)
}
